export const iconList = new Map([
  ['TXT', '文本文件'],
  ['DOCX', 'MicrosoftWord文档'],
  ['PDF', '可移植文档格式'],
  ['XLSX', 'MicrosoftExcel电子表格'],
  ['PPTX', 'MicrosoftPowerPoint演示文稿'],
  ['HTML', '超文本标记语言'],
  ['CSV', '逗号分隔值文件'],
  ['JSON', 'JavaScript对象表示法'],
  ['XML', '可扩展标记语言'],
  ['MP3', '音频文件'],
  ['MP4', '视频文件'],
  ['JPEG', '联合图像专家组照片'],
  ['PNG', '可移植网络图形'],
  ['GIF', '图形交换格式'],
  ['TIFF', '标记图像文件格式'],
  ['BMP', '位图图像'],
  ['AVI', '音频视频互联网文件'],
  ['MOV', 'QuickTime电影'],
  ['WMV', 'Windows媒体视频'],
  ['FLV', 'Flash视频'],
  ['MPG', 'MPEG视频'],
  ['RAR', 'WinRAR压缩存档'],
  ['ZIP', '压缩文件格式'],
  ['7z', '-7-Zip压缩存档'],
  ['JPG', '联合图像专家组照片'],
  ['DOC', '旧版MicrosoftWord文档'],
  ['ODT', '开放文档文本'],
  ['ODS', '开放文档电子表格'],
  ['ODP', '开放文档演示文稿'],
  ['PSD', 'AdobePhotoshop文档'],
  ['EPS', '可编辑的矢量图形'],
  ['SVG', '可缩放矢量图形'],
  ['WAV', '波形音频文件'],
  ['AAC', '高级音频编码'],
  ['FLAC', '自由无损音频编解码器'],
  ['M4A', 'MPEG-4音频文件'],
  ['SWF', '小型网页格式'],
  ['TGA', 'TruevisionTarga图像'],
  ['ICO', '图标文件'],
  ['DDS', 'DirectX纹理文件'],
  ['WMF', 'Windows图元文件'],
  ['EPS', '封装的PostScript'],
  ['RTF', '富文本格式'],
  ['MPEG', '运动图像专家组'],
  ['MPG', 'MPEG视频'],
  ['MID', 'MIDI音频文件'],
  ['HEIC', '高效图像格式'],
  ['PS', 'AdobePostScript文件'],
  ['HEVC', '高效视频编码'],
  ['DWG', 'AutoCAD图纸文件'],
  ['AI', 'AdobeIllustrator文件'],
  ['INDD', 'AdobeInDesign文档'],
  ['CR2', 'CanonRaw图像'],
  ['NEF', 'NikonRaw图像'],
  ['DNG', '数码负片图像'],
  ['ICO', '图标文件'],
  ['GMP', 'GNUMakefile文件'],
  ['TTF', 'TrueType字体文件'],
  ['OTF', '开放字体文件'],
  ['PS', 'PostScript文件'],
  ['SQL', '结构化查询语言文件'],
  ['C', 'C语言源文件'],
  ['CPP', 'C++源文件'],
  ['JAVA', 'Java源文件'],
  ['PY', 'Python源文件'],
  ['JS', 'JavaScript文件'],
  ['CSS', '层叠样式表文件'],
  ['HTM', 'HTML文件'],
  ['ASP', 'ActiveServerPages文件'],
  ['PHP', 'PHP源文件'],
  ['ASPX', 'ASP.NET文件'],
  ['BAT', '批处理文件'],
  ['SH', 'Shell脚本文件'],
  ['EXE', '可执行文件'],
  ['DLL', '动态链接库'],
  ['ISO', '光盘映像文件'],
  ['IMG', '磁盘映像文件'],
  ['BIN', '二进制文件'],
  ['LOG', '日志文件'],
  ['CFG', '配置文件'],
  ['INI', 'INI配置文件'],
  ['DB', '数据库文件'],
  ['MDB', 'MicrosoftAccess数据库'],
  ['SQLITE', 'SQLite数据库文件'],
  ['DBF', '数据库文件'],
  ['TORRENT', '种子文件'],
  ['URL', '统一资源定位符文件'],
  ['HTML', 'HTML网页文件'],
  ['MHT', '单一文件网页'],
  ['RSS', '资源描述框架文件'],
  ['VCF', '电子名片文件'],
  ['ICS', '日历文件'],
  ['MSG', 'Outlook邮件消息'],
  ['PST', 'Outlook数据文件'],
  ['MBOX', '邮箱文件'],
  ['EML', '电子邮件文件'],
  ['DWG', 'AutoCAD图纸文件'],
  ['DXF', 'AutoCADDXF文件'],
  ['STL', '三维打印文件'],
  ['3ds', '3DStudioMax文件'],
])

export  const inputCode = [
//   '`',
//   '~',
//   '1',
//   2
//   3
//   4
//   5
//   6
//   7
//   8
//   9
//   0
//   -
//   =
//   /
//   *
//   +
//   q
// w
// e
// r
// t
// y
// u
// i
// o
// p
// [
//   ]
// \
// a
// s
// d
// f
// g
// h
// j
// k
// l
// ;
// '
//   z
// x
// c
// v
// b
// n
// m
// ,
//   .
// /
//
// ~
//   !
//     @
//   #
// $
// %
//   ^
//   &
//   *


  ];
